import { Level } from './nfa-types';

export const levels: Level[] = [
  {
    id: 1,
    title: "First Steps",
    description: "A simple NFA that accepts strings ending in 'b'.",
    nfa: {
      states: ['q0', 'q1'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0'], b: ['q0', 'q1'] },
        q1: {},
      },
      startState: 'q0',
      acceptStates: ['q1'],
    },
    nodePositions: [
      { id: 'q0', x: 120, y: 150 },
      { id: 'q1', x: 350, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'All strings ending in "b"',
      'All strings starting with "b"',
      'All strings containing "b"',
      'Only the string "b"',
    ],
    correctAnswers: [0],
    explanation: 'From q0, reading "b" branches to both q0 and q1. Since q1 is the accept state, only strings ending in "b" are accepted.',
    exampleInput: 'aab',
  },
  {
    id: 2,
    title: "Double Accept",
    description: "An NFA with multiple accept states accepting strings with 'a' or ending in 'bb'.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q1'], b: ['q0', 'q2'] },
        q1: { a: ['q1'], b: ['q1'] },
        q2: { b: ['q1'] },
      },
      startState: 'q0',
      acceptStates: ['q1'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 350, y: 80 },
      { id: 'q2', x: 350, y: 230 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'Strings containing at least one "a" OR ending in "bb"',
      'Strings with only "a"s',
      'Strings of length 2',
      'All strings over {a, b}',
    ],
    correctAnswers: [0],
    explanation: 'Reading "a" from q0 goes to q1 (accept). Reading "bb" goes q0→q2→q1. So it accepts strings with an "a" or ending in "bb".',
    exampleInput: 'bb',
  },
  {
    id: 3,
    title: "Branching Paths",
    description: "Track multiple active states simultaneously.",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0', 'q1'] },
        q1: { b: ['q2'] },
        q2: { a: ['q3'] },
        q3: {},
      },
      startState: 'q0',
      acceptStates: ['q3'],
    },
    nodePositions: [
      { id: 'q0', x: 80, y: 150 },
      { id: 'q1', x: 210, y: 150 },
      { id: 'q2', x: 330, y: 150 },
      { id: 'q3', x: 450, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'Which of these strings are accepted?',
    options: ['aba', 'aaba', 'ab', 'ba', 'abab'],
    correctAnswers: [0, 1],
    explanation: 'The NFA accepts strings containing the substring "aba". "aba" and "aaba" both contain it.',
    exampleInput: 'aba',
  },
  {
    id: 4,
    title: "Deceptive Machine",
    description: "Looks deterministic but has hidden nondeterminism.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['0', '1'],
      transitions: {
        q0: { '0': ['q0'], '1': ['q0', 'q1'] },
        q1: { '0': ['q2'], '1': ['q2'] },
        q2: {},
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 280, y: 80 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'Strings where the second-to-last symbol is "1"',
      'Strings ending in "1"',
      'Strings with at least two "1"s',
      'Strings of even length',
    ],
    correctAnswers: [0],
    explanation: 'When reading "1", q0 branches to q1. From q1, any next symbol goes to q2 (accept). So the second-to-last symbol must be "1".',
    exampleInput: '010',
  },
  {
    id: 5,
    title: "Epsilon Jump",
    description: "NFAs with ε-transitions can move between states without reading input.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0'], 'ε': ['q1'] },
        q1: { b: ['q2'] },
        q2: { b: ['q2'] },
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 270, y: 150 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'Which strings are accepted?',
    options: ['bb', 'ab', 'abb', 'a', 'b'],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Via the ε-transition, q0 can jump to q1 at any time. Then reading b(s) reaches q2. So: "b" (ε→q1, b→q2), "bb" (ε→q1, b→q2, b→q2), "ab" (a→q0, ε→q1, b→q2), "abb" works similarly. "a" alone never reaches q2.',
    exampleInput: 'ab',
  },
  {
    id: 6,
    title: "Pattern Master",
    description: "A complex NFA combining multiple concepts.",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3', 'q4'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { 'ε': ['q1', 'q3'] },
        q1: { a: ['q2'] },
        q2: { a: ['q2'], b: ['q2'] },
        q3: { b: ['q4'] },
        q4: { a: ['q4'], b: ['q4'] },
      },
      startState: 'q0',
      acceptStates: ['q2', 'q4'],
    },
    nodePositions: [
      { id: 'q0', x: 80, y: 180 },
      { id: 'q1', x: 230, y: 80 },
      { id: 'q2', x: 420, y: 80 },
      { id: 'q3', x: 230, y: 280 },
      { id: 'q4', x: 420, y: 280 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'Non-empty strings starting with "a" or starting with "b"',
      'Strings of length exactly 1',
      'Only "a" and "b"',
      'All non-empty strings over {a, b}',
    ],
    correctAnswers: [3],
    explanation: 'Via ε-transitions, q0 branches to q1 and q3. q1→q2 on "a" (then loops), q3→q4 on "b" (then loops). Together they accept any non-empty string.',
    exampleInput: 'ba',
  },
];
