import { Level } from './nfa-types';

export const levels: Level[] = [
  // === SECTION 1: NFA Basics ===
  {
    id: 1,
    title: "First Steps",
    description: "A simple NFA that accepts strings ending in 'b'.",
    nfa: {
      states: ['q0', 'q1'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0'], b: ['q0', 'q1'] },
        q1: {},
      },
      startState: 'q0',
      acceptStates: ['q1'],
    },
    nodePositions: [
      { id: 'q0', x: 120, y: 150 },
      { id: 'q1', x: 350, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'All strings ending in "b"',
      'All strings starting with "b"',
      'All strings containing "b"',
      'Only the string "b"',
    ],
    correctAnswers: [0],
    explanation: 'From q0, reading "b" branches to both q0 and q1. Since q1 is the accept state, only strings ending in "b" are accepted.',
    exampleInput: 'aab',
  },
  {
    id: 2,
    title: "Double Accept",
    description: "An NFA with multiple accept states accepting strings with 'a' or ending in 'bb'.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q1'], b: ['q0', 'q2'] },
        q1: { a: ['q1'], b: ['q1'] },
        q2: { b: ['q1'] },
      },
      startState: 'q0',
      acceptStates: ['q1'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 350, y: 80 },
      { id: 'q2', x: 350, y: 230 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'Strings containing at least one "a" OR ending in "bb"',
      'Strings with only "a"s',
      'Strings of length 2',
      'All strings over {a, b}',
    ],
    correctAnswers: [0],
    explanation: 'Reading "a" from q0 goes to q1 (accept). Reading "bb" goes q0→q2→q1. So it accepts strings with an "a" or ending in "bb".',
    exampleInput: 'bb',
  },
  {
    id: 3,
    title: "Branching Paths",
    description: "Track multiple active states simultaneously.",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0', 'q1'] },
        q1: { b: ['q2'] },
        q2: { a: ['q3'] },
        q3: {},
      },
      startState: 'q0',
      acceptStates: ['q3'],
    },
    nodePositions: [
      { id: 'q0', x: 80, y: 150 },
      { id: 'q1', x: 210, y: 150 },
      { id: 'q2', x: 330, y: 150 },
      { id: 'q3', x: 450, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'Which of these strings are accepted?',
    options: ['aba', 'aaba', 'ab', 'ba', 'abab'],
    correctAnswers: [0, 1],
    explanation: 'The NFA accepts strings containing the substring "aba". "aba" and "aaba" both contain it. "ab" lacks a trailing "a", "ba" can\'t start the pattern, and "abab" dies after reaching q3.',
    exampleInput: 'aba',
  },

  // === SECTION 2: Nondeterminism Deep Dive ===
  {
    id: 4,
    title: "Deceptive Machine",
    description: "Looks deterministic but has hidden nondeterminism.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['0', '1'],
      transitions: {
        q0: { '0': ['q0'], '1': ['q0', 'q1'] },
        q1: { '0': ['q2'], '1': ['q2'] },
        q2: {},
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 280, y: 80 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'Strings where the second-to-last symbol is "1"',
      'Strings ending in "1"',
      'Strings with at least two "1"s',
      'Strings of even length',
    ],
    correctAnswers: [0],
    explanation: 'When reading "1", q0 branches to q1. From q1, any next symbol goes to q2 (accept). So the second-to-last symbol must be "1". This is a classic NFA , the equivalent DFA needs 4 states!',
    exampleInput: '010',
  },
  {
    id: 5,
    title: "The Empty String",
    description: "What happens when the start state is also an accept state?",
    nfa: {
      states: ['q0', 'q1'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q1'] },
        q1: { b: ['q0'] },
      },
      startState: 'q0',
      acceptStates: ['q0'],
    },
    nodePositions: [
      { id: 'q0', x: 150, y: 150 },
      { id: 'q1', x: 380, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'Which strings are accepted? (ε means the empty string)',
    options: ['ε (empty string)', 'ab', 'a', 'ba', 'abab'],
    correctAnswers: [0, 1, 4],
    explanation: 'Since q0 is both start and accept, ε is accepted (we start in an accept state). "ab" goes q0→q1→q0 (accept). "abab" goes q0→q1→q0→q1→q0 (accept). "a" goes q0→q1 (not accept). "ba" , no transition from q0 on "b".',
    exampleInput: 'ab',
  },

  // === SECTION 3: ε-Transitions ===
  {
    id: 6,
    title: "Epsilon Jump",
    description: "NFAs with ε-transitions can move between states without reading input.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0'], 'ε': ['q1'] },
        q1: { b: ['q2'] },
        q2: { b: ['q2'] },
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 270, y: 150 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'Which strings are accepted?',
    options: ['bb', 'ab', 'abb', 'a', 'b'],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Via the ε-transition, q0 can jump to q1 at any time. Then reading b(s) reaches q2. So: "b" (ε→q1, b→q2), "bb" (ε→q1, b→q2, b→q2), "ab" (a→q0, ε→q1, b→q2), "abb" works similarly. "a" alone never reaches q2.',
    exampleInput: 'ab',
  },

  // === SECTION 4: Closure Properties ===
  {
    id: 7,
    title: "Union Construction",
    description: "Regular languages are closed under union. This NFA was built by combining two simpler NFAs with ε-transitions from a new start state.",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3', 'q4'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { 'ε': ['q1', 'q3'] },
        q1: { a: ['q2'] },
        q2: { a: ['q2'] },
        q3: { b: ['q4'] },
        q4: { b: ['q4'] },
      },
      startState: 'q0',
      acceptStates: ['q2', 'q4'],
    },
    nodePositions: [
      { id: 'q0', x: 80, y: 180 },
      { id: 'q1', x: 230, y: 80 },
      { id: 'q2', x: 420, y: 80 },
      { id: 'q3', x: 230, y: 280 },
      { id: 'q4', x: 420, y: 280 },
    ],
    challengeType: 'multiple-choice',
    question: 'This NFA uses union construction (L₁ ∪ L₂). What language does it accept?',
    options: [
      'a⁺ ∪ b⁺ (one or more a\'s OR one or more b\'s)',
      'All strings over {a, b}',
      'Only "a" and "b"',
      'Strings of length exactly 1',
    ],
    correctAnswers: [0],
    explanation: 'Via ε-transitions, q0 branches to q1 (which accepts a⁺ via q1→q2→q2...) and q3 (which accepts b⁺ via q3→q4→q4...). The union accepts any non-empty string of all a\'s or all b\'s.',
    exampleInput: 'aaa',
  },
  {
    id: 8,
    title: "Concatenation Machine",
    description: "Concatenation (L₁·L₂) is built by connecting accept states of the first NFA to the start of the second via ε-transitions.",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q1'] },
        q1: { a: ['q1'], 'ε': ['q2'] },
        q2: { b: ['q3'] },
        q3: { b: ['q3'] },
      },
      startState: 'q0',
      acceptStates: ['q3'],
    },
    nodePositions: [
      { id: 'q0', x: 80, y: 150 },
      { id: 'q1', x: 210, y: 150 },
      { id: 'q2', x: 330, y: 150 },
      { id: 'q3', x: 460, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'This NFA computes L₁·L₂ (concatenation). Which strings are accepted?',
    options: ['ab', 'aabb', 'ba', 'a', 'abb'],
    correctAnswers: [0, 1, 4],
    explanation: 'L₁ = a⁺ (one or more a\'s), L₂ = b⁺ (one or more b\'s). Concatenation L₁·L₂ = a⁺b⁺. "ab" ✓, "aabb" ✓, "abb" ✓. "ba" has wrong order. "a" has no b\'s.',
    exampleInput: 'aabb',
  },
  {
    id: 9,
    title: "Star Power",
    description: "The Kleene star L* accepts any number of repetitions of strings from L, including ε.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q1'] },
        q1: { b: ['q2'] },
        q2: { 'ε': ['q0'] },
      },
      startState: 'q0',
      acceptStates: ['q0'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 270, y: 150 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'select-all',
    question: 'This NFA implements (ab)*. Which strings are accepted?',
    options: ['ε (empty string)', 'ab', 'abab', 'aabb', 'aba'],
    correctAnswers: [0, 1, 2],
    explanation: 'q0 is start and accept → ε accepted. "ab" goes q0→q1→q2→(ε)q0 → accept. "abab" repeats the cycle twice. "aabb" fails because after the first "a", reading another "a" has no transition from q1. "aba" similarly fails.',
    exampleInput: 'abab',
  },

  // === SECTION 5: Subset Construction & Regex ===
  {
    id: 10,
    title: "Thinking in Subsets",
    description: "The subset construction converts an NFA to an equivalent DFA by tracking sets of states. Each DFA state represents a set of NFA states.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['0', '1'],
      transitions: {
        q0: { '0': ['q0'], '1': ['q0', 'q1'] },
        q1: { '0': ['q2'], '1': ['q2'] },
        q2: {},
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 280, y: 80 },
      { id: 'q2', x: 430, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'In subset construction, after reading "10" from the start, what DFA state (set of NFA states) are you in?',
    options: [
      '{q0}',
      '{q0, q1}',
      '{q0, q2}',
      '{q1, q2}',
    ],
    correctAnswers: [2],
    explanation: 'Start: {q0}. Read "1": from q0 → {q0, q1}. Read "0": from q0 → {q0}, from q1 → {q2}. Union = {q0, q2}. Since q2 ∈ F, this DFA state is an accept state.',
    exampleInput: '10',
  },
  {
    id: 11,
    title: "Regex Match",
    description: "Regular expressions and NFAs describe the same class of languages. Every regex can be converted to an NFA and vice versa.",
    nfa: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { a: ['q0', 'q1'], b: ['q0'] },
        q1: { b: ['q2'] },
        q2: {},
      },
      startState: 'q0',
      acceptStates: ['q2'],
    },
    nodePositions: [
      { id: 'q0', x: 100, y: 150 },
      { id: 'q1', x: 280, y: 150 },
      { id: 'q2', x: 450, y: 150 },
    ],
    challengeType: 'multiple-choice',
    question: 'Which regular expression describes the language of this NFA?',
    options: [
      '(a|b)*ab',
      'a*b*',
      '(ab)*',
      'a(a|b)*b',
    ],
    correctAnswers: [0],
    explanation: 'From q0, reading any mix of a\'s and b\'s keeps you in q0. Reading "a" also branches to q1, then "b" reaches q2 (accept). So the NFA accepts strings ending in "ab" , exactly (a|b)*ab.',
    exampleInput: 'bab',
  },
  {
    id: 12,
    title: "Pattern Master",
    description: "A complex NFA combining ε-transitions, multiple paths, and closure properties. Can you decode it?",
    nfa: {
      states: ['q0', 'q1', 'q2', 'q3', 'q4', 'q5'],
      alphabet: ['a', 'b'],
      transitions: {
        q0: { 'ε': ['q1', 'q3'] },
        q1: { a: ['q2'] },
        q2: { b: ['q2'], 'ε': ['q5'] },
        q3: { b: ['q4'] },
        q4: { a: ['q4'], 'ε': ['q5'] },
        q5: {},
      },
      startState: 'q0',
      acceptStates: ['q5'],
    },
    nodePositions: [
      { id: 'q0', x: 60, y: 180 },
      { id: 'q1', x: 180, y: 80 },
      { id: 'q2', x: 330, y: 80 },
      { id: 'q3', x: 180, y: 280 },
      { id: 'q4', x: 330, y: 280 },
      { id: 'q5', x: 480, y: 180 },
    ],
    challengeType: 'multiple-choice',
    question: 'What language does this NFA accept?',
    options: [
      'ab* ∪ ba* (starts with "a" then any b\'s, OR starts with "b" then any a\'s)',
      'All non-empty strings over {a, b}',
      '(ab)* ∪ (ba)*',
      'Strings of length exactly 2',
    ],
    correctAnswers: [0],
    explanation: 'Via ε from q0: path 1 goes q1→q2 (reads "a" then optional b\'s) → q5. Path 2 goes q3→q4 (reads "b" then optional a\'s) → q5. This is a union of ab* and ba*.',
    exampleInput: 'abbb',
  },
];
